export const ACTION_TYPE = {
    LOADING: 'LOADING',
    CATEGORY: 'CATEGORY',
    CATEGORY_DATA: 'CATEGORY_DATA',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGOUT: 'USER_LOGOUT',
    SHOW_SNACKBAR: 'SHOW_SNACKBAR',
    SHOW_DIALOG: 'SHOW_DIALOG',
    CART: 'CART',
}